item {
    name: "Anthracnose",
    id: 1,
    display_name: "Anthracnose"
}
item {
    name: "Carence minérale",
    id: 2,
    display_name: "Carence minérale"
}
item {
    name: "Dessèchement des bourgeons",
    id: 3,
    display_name: "Dessèchement des bourgeons"
}
item {
    name: "Die-black",
    id: 4,
    display_name: "Die-black"
}
item {
    name: "Dysdercus wolkerii",
    id: 5,
    display_name: "Dysdercus wolkerii"
}
item {
    name: "Oidium",
    id: 6,
    display_name: "Oidium"
}